# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name for card holder', max_length=100, verbose_name='Full Name')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=15, verbose_name='Phone number')),
                ('id_number', models.CharField(help_text='ID number', max_length=10, verbose_name='ID number')),
                ('date_of_birth', models.DateField(help_text='Date of birth', verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Sex type', max_length=10, verbose_name='Sex type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at', verbose_name='Updated at')),
            ],
        ),
    ]
